name: Eagle Animation - Build & package

on:
  push:
    branches:
      - 'master'
      - 'dev'

jobs:
  release:
    name: Build & package
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Clone source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      # Replace by npm ci when it will be fixed
      - name: Install dependencies
        run: |
          rm package-lock.json
          npm i --force

      - name: Build web bundle
        run: npm run build
        env:
          CI: true

      - name: Packaging Windows
        if: matrix.os == 'windows-latest'
        run: npm run package:windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Packaging MacOS
        if: matrix.os == 'macos-latest'
        run: npm run package:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Packaging Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run package:linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload release files
      #   uses: softprops/action-gh-release@v1
      #   if: github.ref == 'refs/heads/master'
      #   with:
      #     files: binaries/@brick-a-brack/*

      #- name: Package app
      #  uses: cryogenicplanet/action-electron-builder@v2
      #  with:
      #    github_token: ${{ secrets.github_token }}
      #    release: true
      #    skip_build: true
      #    skip_install: true
